apiVersion: v1
kind: Pod
metadata:
  name: training-3-pod
spec:
  containers:
    - name: test-container
      image: gcr.io/pradeepnss-213919/training/trainingapp-3:latest
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3
