apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: trainingapp_1
  name: trainingapp_1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: testapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: testapp
    spec:
      containers:
      - image: gcr.io/pradeepnss-213919/imagepull/testapp:1.0
        imagePullPolicy: IfNotPresent
        name: fail
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
