apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: trainingapp-2
  name: trainingapp-2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: trainingapp-2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: crasher
    spec:
      containers:
      - image: gcr.io/pradeepnss-213919/training/trainingapp-2:latest
        imagePullPolicy: Always
        name: crasher
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
