apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trainingapp-8
spec:
  template:
    metadata:
      labels:
        app: trainingapp-8
    spec:
      containers:
        - name: test-container
          image: nginx
          volumeMounts:
          - mountPath: /test
            name: test-volume
      volumes:
      - name: test-volume
        # This GCE PD must already exist (oops!)
        gcePersistentDisk:
          pdName: my-data-disk
          fsType: ext4
