apiVersion: v1
kind: Pod
metadata:
  name: testapp-1
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "3"
      requests:
        cpu: "2"
    args:
    - -cpus
    - "2"
