apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: need-label
            operator: In
            values:
            - test
  containers:
  - name: with-node-affinity
    image: k8s.gcr.io/pause:2.0
